# Generated by Django 4.2 on 2023-04-27 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='reset_password_token',
        ),
        migrations.DeleteModel(
            name='ForgetPassword',
        ),
    ]
