# Generated by Django 4.2 on 2023-05-02 04:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_date_created_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_password_reset_verified',
        ),
    ]
