# Generated by Django 4.2 on 2023-04-29 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_is_verified_user_is_email_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_password_reset_verified',
            field=models.BooleanField(default=False),
        ),
    ]
