# Generated by Django 4.2 on 2023-04-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_password_reset_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='password_reset_verification_code',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
    ]
