# Generated by Django 4.2 on 2023-05-10 04:21

import accounts.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_is_password_reset_verified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(validators=[accounts.validators.validate_password]),
        ),
    ]
